/******************************************************************
 * Version      Date                Name            Description
 * V1.0         29-08-2024          Developer1      Add method implemeted
 * 
 *******************************************************************/

public with sharing class Calculate {
    public Calculate() {

    }
    public integer add(integer a, integer b){
        return a+b;
    }
}